githubApiToken: ${GITHUB_API_TOKEN:-}
githubMapsOrgName: triplea-maps


# If map indexing is enabled, it will begin shortly after server startup.
# If disabled no map indexing will occur.
mapIndexingEnabled: ${MAP_INDEXING_ENABLED:-false}

# How often between map indexing runs. On each map indexing run we will
# index all maps. If the previous map indexing run is still going
# we will then have multiple indexing jobs running at the same time.
# To avoid overlapping indexing jobs, this value needs to be greater than:
#  (number of maps) * (processing time) * (indexingTaskDelaySeconds / 60)
mapIndexingPeriodMinutes: ${MAP_INDEXING_PERIOD_MINUTES:-300}

# Time period in seconds between indexing each individual map. This must
# be configured to avoid github API rate limiting.
# Eg:
#      1 -> one indexing task per second -> 3600 requests  per hour.
#      5 -> one indexing task every 5 seconds -> 720 requests per hour.
#     60 -> one indexing task per minute -> 60 requests per hour.
#    120 -> one indexing task every other minute -> 30 requests per hour.
# Unauthenticated Github API requests are limited to 60 request per hour.
# Authenticated Github API requests are limited to 1000 requests per hour.
indexingTaskDelaySeconds: ${MAP_INDEXING_DELAY_SECONDS:-120}

# Whether to print out SQL statements as executed, useful for debugging.
logSqlStatements: false

database:
  driverClass: org.postgresql.Driver
  user: ${DATABASE_USER:-maps_user}
  password: ${DATABASE_PASSWORD:-maps_user}
  url: jdbc:postgresql://${DB_URL:-localhost:5432/maps_db}
