server:
  applicationConnectors:
    - type: http
      port: ${HTTP_PORT:-8080}
      # useForwardedHeaders is important for when behind a reverse proxy (NGINX)
      # Without this 'getRemoteAddr' will return the IP of the reverse proxy server.
      # By default when building locally useForwardedPorts should be 'false', but
      # for all other environments that do have a NGINX server, the value should be
      # set to true.
      useForwardedHeaders: ${USE_FORWARDED_HEADERS:-false}
  adminConnectors: []
