# Launches a maps server with database

services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/init/01-init-database.sql:/docker-entrypoint-initdb.d/01-init-database.sql
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: echo 'select 1' | psql -h localhost -U postgres  | grep -q '1 row'
      interval: 3s
      retries: 10
      timeout: 3s
  flyway:
    build:
      context: database/
      dockerfile: Dockerfile
    command: >
      -locations=filesystem:/flyway/sql
      -connectRetries=6
      -connectRetriesInterval=5
      -user=support_user
      -password=support_user
      -url=jdbc:postgresql://database:5432/support_db
      -ignoreMigrationPatterns="repeatable:missing"
      migrate
    depends_on:
      - database
  server:
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=support_user
      - DATABASE_PASSWORD=support_user
      - DB_URL=database:5432/support_db
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      flyway:
         condition: service_completed_successfully
