# Runs all build checks on any pull request or merges to master
name: Pull Request
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run Build Checks
        run: make testForPr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
